[java]
jdk = "openjdk 17.0.6 lts"
organisation = "adoptium eclipse temurin"

[build]
tool = "maven"

[editors]
jetbrains = [ "intellij idea community", "fleet",]
microsoft = [ "visual studio code",]

[structure]
source_dir = "src/main/java/**"
resources_dir = "src/main/resources/**"
test_dir = "test/java/**"
build_dir = "target"

[git]
visibility = "private"

[database]
type = "mysql"
driver = "com.mysql.cj.jdbc.Driver"
url = "jdbc:mysql://localhost:3306/library"
username = "root"
password = "dbpassword"

[dependencies]
openjfx = "17.0.2"
mysql_connector = "8.0.32"
junit = "5.9.1"

[project]
name = "Library Loans System"
main_function = "winchester.library.Main.main"

[project.version]
major = 1
minor = 0
revision = 2
build = 1055
