[Project]
Name = "Library Loans System"
For = "BSc (Hons) Computer Science: BS2202 Object Orientated Software Development"
Description = ""
Version = "1.0.2.1259"
Entrypoint = "winchester.library.Main.main"
Language = "Java ^17 LTS"
Build = "Maven"

[Git]
Initialised = "Public from November 2023"

[Structure]
Source = ["src/main/java/**.java"]
Assets = ["src/main/resources/**"]
Tests = ["test/java/**"]

[Output]
Build = "target"
Exports = "exports"

[Database]
Type = "MySQL"
Data = "data/library.sql"

[Dependencies]
JavaFX = "17.0.2"
MySQL-Connector = "8.0.32"
JUnit = "5.9.1"